"""initial schema

Revision ID: 201d84df5d46
Revises: 
Create Date: 2025-10-08 10:52:35.168213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201d84df5d46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_members_username'), ['username'], unique=True)

    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('reservation_time', sa.Time(), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_reservation_date'), ['reservation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_status'), ['status'], unique=False)

    op.create_table('member_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_notes_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_notes_reservation_id'), ['reservation_id'], unique=False)

    op.create_table('reservation_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('fee_applied', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservation_fees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_fees_reservation_id'), ['reservation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_fees_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_fees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_fees_rule_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_fees_reservation_id'))

    op.drop_table('reservation_fees')
    with op.batch_alter_table('member_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_notes_reservation_id'))
        batch_op.drop_index(batch_op.f('ix_member_notes_member_id'))
        batch_op.drop_index(batch_op.f('ix_member_notes_created_at'))

    op.drop_table('member_notes')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_status'))
        batch_op.drop_index(batch_op.f('ix_reservations_reservation_date'))
        batch_op.drop_index(batch_op.f('ix_reservations_member_id'))

    op.drop_table('reservations')
    op.drop_table('rules')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_username'))
        batch_op.drop_index(batch_op.f('ix_members_email'))

    op.drop_table('members')
    # ### end Alembic commands ###
