"""Add fee_type to rules

Revision ID: 30e7ff247201
Revises: 201d84df5d46
Create Date: 2025-10-10 14:51:24.106501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e7ff247201'
down_revision = '201d84df5d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_column('fee_type')

    # ### end Alembic commands ###
