"""Update rules and reservation_fees schema

Revision ID: b3386073d499
Revises: dfc65dd2f610
Create Date: 2025-10-06 13:18:48.137461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3386073d499'
down_revision = 'dfc65dd2f610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_fees', schema=None) as batch_op:
        batch_op.alter_column('fee_applied',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_fees', schema=None) as batch_op:
        batch_op.alter_column('fee_applied',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
